# Generated by Django 5.2.7 on 2025-10-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
    ]
