# Generated by Django 5.2.6 on 2025-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_gender_remove_account_role'),
        ('detail_product', '0002_remove_product_last_updated_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='detail_product.product'),
        ),
    ]
