# Generated by Django 5.2.7 on 2025-11-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
    ]
