# Generated by Django 5.2.7 on 2025-10-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_product', '0003_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
